spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  application:
    name: api

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
    error:
      include-stacktrace: never
